export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

// login
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";
export const FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST";
export const FETCH_LOGIN_FAILURE = "FETCH_LOGIN_FAILURE";

// login promise
export const LOAD_LOGIN = "LOAD_LOGIN";
export const LOAD_LOGIN_FULFILLED = "LOAD_LOGIN_FULFILLED";
export const LOAD_LOGIN_REJECTED = "LOAD_LOGIN_REJECTED";
export const LOAD_LOGIN_PENDING = "LOAD_LOGIN_PENDING";